import { MediaItem } from '@/types/media';

export const POPULAR_AMERICAN_CATALOG: MediaItem[] = [
  // --- MOVIES ---
  {
    id: 27205,
    tmdbId: 27205,
    title: 'Inception',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1518676599625-5d51d8b67123?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2010-07-15',
    overview: 'Cobb, a skilled thief who steals corporate secrets through dream-sharing technology, is given the inverse task of planting an idea into the mind of a C.E.O.',
    genres: ['Action', 'Science Fiction', 'Adventure'],
    directors: ['Christopher Nolan'],
    cast: [{ id: 6193, name: 'Leonardo DiCaprio', character: 'Dom Cobb', profilePath: null }, { id: 24045, name: 'Joseph Gordon-Levitt', character: 'Arthur', profilePath: null }],
    voteAverage: 8.4,
    tagline: 'Your mind is the scene of the crime.',
    runtime: 148,
  },
  {
    id: 155,
    tmdbId: 155,
    title: 'The Dark Knight',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2008-07-16',
    overview: 'Batman raises the stakes in his war on crime. With Harvey Dent and Jim Gordon, Batman sets out to dismantle criminal organizations in Gotham City.',
    genres: ['Drama', 'Action', 'Crime'],
    directors: ['Christopher Nolan'],
    cast: [{ id: 3894, name: 'Christian Bale', character: 'Bruce Wayne / Batman', profilePath: null }, { id: 1810, name: 'Heath Ledger', character: 'Joker', profilePath: null }],
    voteAverage: 8.5,
    tagline: 'Welcome to a world without rules.',
    runtime: 152,
  },
  {
    id: 278,
    tmdbId: 278,
    title: 'The Shawshank Redemption',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/9cqN1XFea8hNmyOvqw9JvAcBwXi.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1994-09-23',
    overview: 'Imprisoned in the 1940s for a double murder he didn\'t commit, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    genres: ['Drama', 'Crime'],
    directors: ['Frank Darabont'],
    cast: [{ id: 504, name: 'Tim Robbins', character: 'Andy Dufresne', profilePath: null }, { id: 192, name: 'Morgan Freeman', character: 'Ellis Boyd "Red" Redding', profilePath: null }],
    voteAverage: 8.7,
    tagline: 'Fear can hold you prisoner. Hope can set you free.',
    runtime: 142,
  },
  {
    id: 238,
    tmdbId: 238,
    title: 'The Godfather',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1972-03-14',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When Don Vito Corleone is wounded, his youngest son Michael steps into the underworld.',
    genres: ['Drama', 'Crime'],
    directors: ['Francis Ford Coppola'],
    cast: [{ id: 3084, name: 'Marlon Brando', character: 'Vito Corleone', profilePath: null }, { id: 1158, name: 'Al Pacino', character: 'Michael Corleone', profilePath: null }],
    voteAverage: 8.7,
    tagline: 'An offer you can\'t refuse.',
    runtime: 175,
  },
  {
    id: 13,
    tmdbId: 13,
    title: 'Forrest Gump',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9Lw1q0h05.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1994-06-23',
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—each time, discovering that his love, Jenny, remains elusive.',
    genres: ['Comedy', 'Drama', 'Romance'],
    directors: ['Robert Zemeckis'],
    cast: [{ id: 31, name: 'Tom Hanks', character: 'Forrest Gump', profilePath: null }, { id: 88, name: 'Robin Wright', character: 'Jenny Curran', profilePath: null }],
    voteAverage: 8.5,
    tagline: 'The world will never be the same once you\'ve seen it through the eyes of Forrest Gump.',
    runtime: 142,
  },
  {
    id: 157336,
    tmdbId: 157336,
    title: 'Interstellar',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2014-11-05',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass human space travel and save humanity.',
    genres: ['Adventure', 'Drama', 'Science Fiction'],
    directors: ['Christopher Nolan'],
    cast: [{ id: 10296, name: 'Matthew McConaughey', character: 'Cooper', profilePath: null }, { id: 1813, name: 'Anne Hathaway', character: 'Brand', profilePath: null }],
    voteAverage: 8.4,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    runtime: 169,
  },
  {
    id: 603,
    tmdbId: 603,
    title: 'The Matrix',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1999-03-31',
    overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genres: ['Action', 'Science Fiction'],
    directors: ['Lana Wachowski', 'Lilly Wachowski'],
    cast: [{ id: 6384, name: 'Keanu Reeves', character: 'Neo', profilePath: null }, { id: 2975, name: 'Laurence Fishburne', character: 'Morpheus', profilePath: null }],
    voteAverage: 8.2,
    tagline: 'Welcome to the Real World.',
    runtime: 136,
  },
  {
    id: 550,
    tmdbId: 550,
    title: 'Fight Club',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1518676599625-5d51d8b67123?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1999-10-15',
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
    genres: ['Drama'],
    directors: ['David Fincher'],
    cast: [{ id: 819, name: 'Edward Norton', character: 'The Narrator', profilePath: null }, { id: 287, name: 'Brad Pitt', character: 'Tyler Durden', profilePath: null }],
    voteAverage: 8.4,
    tagline: 'Mischief. Mayhem. Soap.',
    runtime: 139,
  },
  {
    id: 680,
    tmdbId: 680,
    title: 'Pulp Fiction',
    mediaType: 'movie',
    posterPath: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=500&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1994-09-10',
    overview: 'A burger-loving hitman, his philosophical partner, a drug-addled gangster\'s moll and a boxer converge in four tales of violence and redemption.',
    genres: ['Thriller', 'Crime'],
    directors: ['Quentin Tarantino'],
    cast: [{ id: 8891, name: 'John Travolta', character: 'Vincent Vega', profilePath: null }, { id: 2231, name: 'Samuel L. Jackson', character: 'Jules Winnfield', profilePath: null }],
    voteAverage: 8.5,
    tagline: 'Just because you are a character doesn\'t mean that you have character.',
    runtime: 154,
  },
  {
    id: 872585,
    tmdbId: 872585,
    title: 'Oppenheimer',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2023-07-19',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
    genres: ['Drama', 'History'],
    directors: ['Christopher Nolan'],
    cast: [{ id: 2038, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profilePath: null }],
    voteAverage: 8.1,
    tagline: 'The world forever changes.',
    runtime: 180,
  },
  {
    id: 693134,
    tmdbId: 693134,
    title: 'Dune: Part Two',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2024-02-27',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge.',
    genres: ['Science Fiction', 'Adventure'],
    directors: ['Denis Villeneuve'],
    cast: [{ id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profilePath: null }],
    voteAverage: 8.3,
    runtime: 166,
  },
  {
    id: 299536,
    tmdbId: 299536,
    title: 'Avengers: Infinity War',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/7WsyChL61vj2JDUB9R2eP0iT.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2018-04-25',
    overview: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation puts an end to the universe.',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    directors: ['Anthony Russo', 'Joe Russo'],
    cast: [{ id: 3223, name: 'Robert Downey Jr.', character: 'Tony Stark / Iron Man', profilePath: null }, { id: 16828, name: 'Chris Evans', character: 'Steve Rogers / Captain America', profilePath: null }],
    voteAverage: 8.3,
    runtime: 149,
  },
  {
    id: 597,
    tmdbId: 597,
    title: 'Titanic',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/9cqN1XFea8hNmyOvqw9JvAcBwXi.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1997-11-18',
    overview: '101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later, to her granddaughter.',
    genres: ['Drama', 'Romance'],
    directors: ['James Cameron'],
    cast: [{ id: 6193, name: 'Leonardo DiCaprio', character: 'Jack Dawson', profilePath: null }, { id: 204, name: 'Kate Winslet', character: 'Rose DeWitt Bukater', profilePath: null }],
    voteAverage: 7.9,
    runtime: 194,
  },
  {
    id: 299534,
    tmdbId: 299534,
    title: 'Avengers: Endgame',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2019-04-24',
    overview: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.',
    genres: ['Adventure', 'Science Fiction', 'Action'],
    directors: ['Anthony Russo', 'Joe Russo'],
    cast: [{ id: 3223, name: 'Robert Downey Jr.', character: 'Tony Stark / Iron Man', profilePath: null }],
    voteAverage: 8.3,
    runtime: 181,
  },
  {
    id: 346698,
    tmdbId: 346698,
    title: 'Barbie',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/iuFC081BhV8f9rmW3wAAtM7oBwI.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2023-07-19',
    overview: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    directors: ['Greta Gerwig'],
    cast: [{ id: 234352, name: 'Margot Robbie', character: 'Barbie', profilePath: null }, { id: 30614, name: 'Ryan Gosling', character: 'Ken', profilePath: null }],
    voteAverage: 7.1,
    runtime: 114,
  },
  {
    id: 361743,
    tmdbId: 361743,
    title: 'Top Gun: Maverick',
    mediaType: 'movie',
    posterPath: 'https://image.tmdb.org/t/p/w500/62HCicF2L8vXY9yRwxR98mOzXi7.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2022-05-24',
    overview: 'After thirty years of service as a top naval aviator, Pete "Maverick" Mitchell is where he belongs, pushing the envelope as a courageous test pilot.',
    genres: ['Action', 'Drama'],
    directors: ['Joseph Kosinski'],
    cast: [{ id: 500, name: 'Tom Cruise', character: 'Pete "Maverick" Mitchell', profilePath: null }],
    voteAverage: 8.2,
    runtime: 131,
  },

  // --- TV SHOWS ---
  {
    id: 1396,
    tmdbId: 1396,
    title: 'Breaking Bad',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2008-01-20',
    overview: 'Walter White, a chemistry teacher diagnosed with inoperable lung cancer, turns to manufacturing and selling methamphetamine with a former student in order to secure his family\'s future.',
    genres: ['Drama', 'Crime'],
    directors: ['Vince Gilligan'],
    cast: [{ id: 17419, name: 'Bryan Cranston', character: 'Walter White', profilePath: null }, { id: 84497, name: 'Aaron Paul', character: 'Jesse Pinkman', profilePath: null }],
    voteAverage: 8.9,
    tagline: 'Change the equation.',
  },
  {
    id: 2316,
    tmdbId: 2316,
    title: 'The Office (US)',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjN3mVTZ2clC.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2005-03-24',
    overview: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium at Dunder Mifflin Paper Company in Scranton, PA.',
    genres: ['Comedy'],
    directors: ['Greg Daniels'],
    cast: [{ id: 26261, name: 'Steve Carell', character: 'Michael Scott', profilePath: null }, { id: 104752, name: 'John Krasinski', character: 'Jim Halpert', profilePath: null }],
    voteAverage: 8.6,
  },
  {
    id: 1668,
    tmdbId: 1668,
    title: 'Friends',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=780&q=80',
    releaseDate: '1994-09-22',
    overview: 'Six young adults in their 20s and 30s living in Manhattan, New York City, navigate personal and professional lives while supporting each other through thick and thin.',
    genres: ['Comedy'],
    directors: ['David Crane', 'Marta Kauffman'],
    cast: [{ id: 4495, name: 'Jennifer Aniston', character: 'Rachel Green', profilePath: null }, { id: 1472, name: 'Courteney Cox', character: 'Monica Geller', profilePath: null }],
    voteAverage: 8.5,
  },
  {
    id: 95396,
    tmdbId: 95396,
    title: 'Severance',
    mediaType: 'tv',
    posterPath: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=500&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2022-02-17',
    overview: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.',
    genres: ['Sci-Fi & Fantasy', 'Drama'],
    directors: ['Ben Stiller'],
    cast: [{ id: 20580, name: 'Adam Scott', character: 'Mark Scout', profilePath: null }],
    voteAverage: 8.6,
  },
  {
    id: 76331,
    tmdbId: 76331,
    title: 'Succession',
    mediaType: 'tv',
    posterPath: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=500&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2018-06-03',
    overview: 'The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company.',
    genres: ['Drama'],
    directors: ['Jesse Armstrong'],
    cast: [{ id: 3267, name: 'Brian Cox', character: 'Logan Roy', profilePath: null }],
    voteAverage: 8.5,
  },
  {
    id: 66732,
    tmdbId: 66732,
    title: 'Stranger Things',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2016-07-15',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments and supernatural forces.',
    genres: ['Sci-Fi & Fantasy', 'Drama'],
    directors: ['The Duffer Brothers'],
    cast: [{ id: 1356210, name: 'Millie Bobby Brown', character: 'Eleven', profilePath: null }],
    voteAverage: 8.6,
  },
  {
    id: 125988,
    tmdbId: 125988,
    title: 'The Bear',
    mediaType: 'tv',
    posterPath: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=500&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2022-06-23',
    overview: 'A young chef from the fine dining world returns to Chicago to run his family’s Italian beef sandwich shop after a heartbreaking death.',
    genres: ['Drama', 'Comedy'],
    directors: ['Christopher Storer'],
    cast: [{ id: 1269389, name: 'Jeremy Allen White', character: 'Carmy Berzatto', profilePath: null }],
    voteAverage: 8.5,
  },
  {
    id: 60059,
    tmdbId: 60059,
    title: 'Better Call Saul',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/f2t4JbLbh2j7r0d2t.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2015-02-08',
    overview: 'The trials and tribulations of criminal lawyer Jimmy McGill in the time leading up to establishing his strip-mall law office in Albuquerque, New Mexico.',
    genres: ['Crime', 'Drama'],
    directors: ['Vince Gilligan', 'Peter Gould'],
    cast: [{ id: 59410, name: 'Bob Odenkirk', character: 'Jimmy McGill / Saul Goodman', profilePath: null }],
    voteAverage: 8.6,
  },
  {
    id: 100088,
    tmdbId: 100088,
    title: 'The Last of Us',
    mediaType: 'tv',
    posterPath: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2023-01-15',
    overview: 'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie out of an oppressive quarantine zone.',
    genres: ['Drama', 'Action & Adventure'],
    directors: ['Craig Mazin'],
    cast: [{ id: 1253360, name: 'Pedro Pascal', character: 'Joel Miller', profilePath: null }],
    voteAverage: 8.6,
  },
  {
    id: 1399,
    tmdbId: 1399,
    title: 'Game of Thrones',
    mediaType: 'tv',
    posterPath: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=500&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2011-04-17',
    overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.',
    genres: ['Sci-Fi & Fantasy', 'Drama'],
    directors: ['David Benioff', 'D.B. Weiss'],
    cast: [{ id: 49339, name: 'Kit Harington', character: 'Jon Snow', profilePath: null }],
    voteAverage: 8.4,
  },
  {
    id: 82856,
    tmdbId: 82856,
    title: 'The Mandalorian',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2019-11-12',
    overview: 'After the stories of Jango and Boba Fett, another warrior emerges in the Star Wars universe. The Mandalorian is set after the fall of the Empire.',
    genres: ['Sci-Fi & Fantasy', 'Action & Adventure'],
    directors: ['Jon Favreau'],
    cast: [{ id: 1253360, name: 'Pedro Pascal', character: 'Din Djarin / The Mandalorian', profilePath: null }],
    voteAverage: 8.4,
  },
  {
    id: 73586,
    tmdbId: 73586,
    title: 'Yellowstone',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/pe2syG9m4qT40HjBv5JbQ1b8.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2018-06-20',
    overview: 'Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States.',
    genres: ['Western', 'Drama'],
    directors: ['Taylor Sheridan'],
    cast: [{ id: 1269, name: 'Kevin Costner', character: 'John Dutton', profilePath: null }],
    voteAverage: 8.2,
  },
  {
    id: 110492,
    tmdbId: 110492,
    title: 'Ted Lasso',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/3r2.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2020-08-14',
    overview: 'An American football coach is hired to manage a British soccer team. What he lacks in knowledge, he makes up for with optimism.',
    genres: ['Comedy', 'Drama'],
    directors: ['Jason Sudeikis', 'Bill Lawrence'],
    cast: [{ id: 35048, name: 'Jason Sudeikis', character: 'Ted Lasso', profilePath: null }],
    voteAverage: 8.5,
  },
  {
    id: 114472,
    tmdbId: 114472,
    title: 'The White Lotus',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/4t0.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2021-07-11',
    overview: 'A sharp social satire following the exploits of various employees and guests at an exclusive Hawaiian resort over the span of one highly volatile week.',
    genres: ['Comedy', 'Drama', 'Mystery'],
    directors: ['Mike White'],
    cast: [{ id: 31168, name: 'Jennifer Coolidge', character: 'Tanya McQuoid', profilePath: null }],
    voteAverage: 8.0,
  },
  {
    id: 85552,
    tmdbId: 85552,
    title: 'Euphoria',
    mediaType: 'tv',
    posterPath: 'https://image.tmdb.org/t/p/w500/3r2eu.jpg',
    backdropPath: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=780&q=80',
    releaseDate: '2019-06-16',
    overview: 'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
    genres: ['Drama'],
    directors: ['Sam Levinson'],
    cast: [{ id: 505710, name: 'Zendaya', character: 'Rue Bennett', profilePath: null }],
    voteAverage: 8.3,
  },
];
